### ISSUE TITLE
Presented By: not rendered when viewing abstract

### ISSUE THREAD

**Issue by rpcme** [mojoconf/MCT#55]
[04:46:03] riche:   batman: I noticed when looking at a submitted abstract, there is a line "Presented by" but it doesn't render the name of the presenter
[04:46:45] riche:   Profile -> my presentations -> click abstract

![render](https://cloud.githubusercontent.com/assets/2113279/6937639/cb2ea9dc-d82a-11e4-97b6-66060f1653da.png)

**Comment by jhthorsen** [comment]
I think it's because the user doesn't have a name. I guess we could fallback to github username. Will write a unit test to confirm.

I'm also considering making the name/username clickable to a public profile page, where we display:
- Name / Github username
- Profile picture
- Home page url

If you are admin (or logged in as the current user), you will then see the complete profile.

Not sure if there's any issue with that. Do we need a user agreement?

**Comment by jhthorsen** [comment]
Ah! Opting in by github already allows us to use the public information.

**Comment by jhthorsen** [comment]
@rpcme: Whenever you submit an issue, please mention the direct url as well. It saves time.
